
server:
    port: 5000
spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
        driver-class-name: org.h2.Driver

