
server:
    port: 5000

spring:
  jackson:
    default-property-inclusion: non_null

management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: health

logging.level:
  org.zalando.logbook: trace