
server:
    port: 5000

keycloak:
  serverUrl: ${SERVER_URL}
  realm: ${REALM}
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  username: ${USERNAME}
  password: ${PASSWORD}
  grantType: ${GRANT_TYPE}

spring:
  jackson:
    default-property-inclusion: non_null